---
title: 'Changing Rivers MS'
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(macrosheds)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(ggthemes)
library(trend) #for Sen's slope
library(plotly)
library(ggrepel)
```

```{r config, include = FALSE}

# dmns <- c('hbef', 'fernow')
vwc_vars <- c('pH', 'NO3_N', 'SO4_S', 'Na', 'K', 'Ca', 'Mg', 'SiO2_Si', 'DOC',
              # 'Chla', 'Chl', 'Mn', 'Fe',
              'DIC', 'NH4_N', 'SiO2_S', 'PO4', 'orthophosphate_P',
              'TSS', 'TP', 'TN', 'F', 'Cl')
non_vwc_vars <- c('spCond', 'temp')
salt_vars <- c('Ca', 'Mg', 'Na', 'K', 'SO4_S', 'NO3_N', 'Cl')#, 'NH4_N', 'F', 'alk')
np_vars <- c('NO3_N', 'PO4_P')
# chuck_sites <- c('QT', 'QS', 'Q3')
chuck_sites <- c()

ms_root <- '~/git/macrosheds/macrosheds_dataset/'
```

```{r helpers, include = FALSE}

has_xiny <- function(wy, x, y) {
  #x wateryears represented over a y year span
  wy <- sort(unique(wy))
  n  <- length(wy)
  if (n < x) return(FALSE)

  for (i in seq_len(n)) {
    if (sum(wy >= wy[i] & wy <= wy[i] + (y - 1)) >= x)
      return(TRUE)
  }
  FALSE
}
```

```{r load, include = FALSE}

# ms_download_core_data(ms_root, domains = 'all')

sites <- ms_load_sites()
conc <- ms_load_product(ms_root, 'stream_chemistry', warn = FALSE)
# pconc <- ms_load_product(ms_root, 'precip_chemistry')
q <- ms_load_product(ms_root, 'discharge', warn = FALSE)
# p <- ms_load_product(ms_root, 'precipitation')

cmls <- read_csv('camels_chem/Camels_chem_1980_2018.csv', guess_max = 40000)
```

```{r prep, include = FALSE}

cmls_sites <- cmls %>% 
  select(domain = region_name,
         site_code = gauge_name) %>% 
  distinct()
sites <- bind_rows(sites, cmls_sites)

cmls <- cmls %>% 
  mutate(pH = coalesce(ph, ph2),
         SO4_S = so4 * (32.06 / 96.06), #SO4 to SO4-S
         discharge = q_daily * 28.31685) %>% #cfs to L/s
  select(#domain = region_name,
         site_code = gauge_name,
         date = sample_timestamp,
         Cl = cl, Na = na, K = k, Mg = mg, NO3 = no3, SO4_S, Ca = ca,
         temp, pH, DO = o, discharge) %>% #alk, etc.
  mutate(date = as.Date(mdy_hm(date))) %>% 
  group_by(date, site_code) %>% 
  summarize(across(everything(), \(x) mean(x, na.rm = TRUE)),
            .groups = 'drop') %>% 
  pivot_longer(Cl:discharge, names_to = 'var', values_to = 'val')

q <- bind_rows(q,
               filter(cmls, var == 'discharge'))

conc <- bind_rows(conc,
                  filter(cmls, var != 'discharge'))

vwc_s <- conc %>%
  filter(var %in% vwc_vars) %>% 
  mutate(val = if_else(var == 'pH', 10^(-val), val)) %>%
  left_join(select(sites, domain, site_code), by = 'site_code') %>%
  select(domain, site_code, date, var, val) %>%
  left_join(
    select(q, date, site_code, q = val),
    by = c('date', 'site_code')
  ) %>%
  filter(!is.na(val), !is.na(q)) %>%
  mutate(
    wy = if_else(month(date) >= 10, year(date) + 1, year(date)),
    q = q * 86400 #L
  ) %>%
  group_by(domain, site_code, wy, var) %>%
  summarize(vwc = sum(val * q) / sum(q), .groups = 'drop') %>%
  mutate(
    vwc = if_else(var == 'pH', -log10(pmax(vwc, .Machine$double.xmin)), vwc)
  ) %>%
  filter(! site_code %in% chuck_sites) %>% 
  group_by(site_code, var) %>% 
  filter(has_xiny(wy, 10, 15)) %>% 
  ungroup() %>% 
  filter(! is.na(vwc))

d_s <- conc %>%
  # filter(var %in% non_vwc_vars) %>% 
  left_join(select(sites, domain, site_code), by = 'site_code') %>%
  select(domain, site_code, date, var, val) %>%
  filter(!is.na(val)) %>%
  mutate(
    wy = if_else(month(date) >= 10, year(date) + 1, year(date)),
  ) %>%
  group_by(domain, site_code, wy, var) %>%
  summarize(val = median(val, na.rm = TRUE),
            .groups = 'drop') %>% 
  filter(! site_code %in% chuck_sites) %>% 
  group_by(site_code, var) %>% 
  filter(has_xiny(wy, 10, 15)) %>% 
  ungroup()

# q_conform <- q %>%
#   mutate(wy = if_else(month(date) >= 10, year(date) + 1, year(date))) %>%
#   left_join(select(sites, domain, site_code, ws_area_ha), by = 'site_code') %>%
#   filter(! is.na(val)) %>%
#   mutate(val = val * 86400 / ws_area_ha / 10000) %>%
#   group_by(domain, site_code, wy) %>%
#   summarize(val = sum(val, na.rm = TRUE), .groups = 'drop') %>%
#   mutate(var = 'hyd_flux_mm') %>%
#   select(domain, site_code, wy, var, vwc = val)

# vwc_s <- bind_rows(vwc_s, q_conform)
```

```{r Sen slope, include = FALSE}

vwc_trend <- vwc_s %>%
  group_by(domain, site_code, var) %>%
  arrange(wy) %>% 
  summarize(
    sen_fit = list(sens.slope(vwc)),
    .groups = 'drop'
  ) %>%
  mutate(
    sen_slope = map_dbl(sen_fit, ~ .x$estimates[["Sen's slope"]]),
    p_value = map_dbl(sen_fit, ~ .x$p.value)
  ) %>%
  select(-sen_fit)

vwc_trend <- vwc_trend %>%
  mutate(
    sig = !is.na(p_value) & p_value < 0.05,
    trend_cat = case_when(
      !sig ~ 'nonsig',
      sen_slope > 0 ~ 'pos',
      sen_slope < 0 ~ 'neg',
      TRUE ~ 'nonsig' #such thing as 0 slope and sig?
    )
  )

vwc_plot <- vwc_s %>%
  left_join(vwc_trend, by = c('domain', 'site_code', 'var'))


d_trend <- d_s %>%
  filter(var %in% non_vwc_vars) %>% 
  group_by(domain, site_code, var) %>%
  arrange(wy) %>% 
  summarize(
    sen_fit = list(sens.slope(val)),
    .groups = 'drop'
  ) %>%
  mutate(
    sen_slope = map_dbl(sen_fit, ~ .x$estimates[["Sen's slope"]]),
    p_value = map_dbl(sen_fit, ~ .x$p.value)
  ) %>%
  select(-sen_fit)

d_trend <- d_trend %>%
  mutate(
    sig = !is.na(p_value) & p_value < 0.05,
    trend_cat = case_when(
      !sig ~ 'nonsig',
      sen_slope > 0 ~ 'pos',
      sen_slope < 0 ~ 'neg',
      TRUE ~ 'nonsig' #such thing as 0 slope and sig?
    )
  )

d_plot <- d_s %>%
  right_join(d_trend, by = c('domain', 'site_code', 'var'))
```

### Temporal trends 

```{r all var triends (faceted), echo = FALSE, fig.width = 16}
p <- vwc_plot %>% 
  ggplot(aes(x = wy, y = vwc, group = site_code, color = trend_cat,
             text = paste(
               "Domain:", domain,
               "<br>Site:", site_code,
               "<br>Var:", var,
               "<br>WY:", wy,
               "<br>WVC:", signif(vwc, 3),
               "<br>Sen slope:", signif(sen_slope, 3),
               "<br>p:", signif(p_value, 3)
             ))) +
  geom_line(aes(alpha = 0.3)) +
  scale_color_manual(
    values = c(
      pos    = 'firebrick3',
      neg    = 'dodgerblue3',
      nonsig = 'gray50'
      # flat   = 'gray50'
    ),
    # na.value = 'gray80'
  ) +
  scale_alpha_identity() +
  facet_wrap(~ var, scales = 'free_y') +
  labs(
    x = 'Water year',
    y = 'Volume-weighted concentration (mg/L)',
    color = 'Trend',
    title = 'VWC'
  ) +
  theme_few()

ggplotly(p, tooltip = 'text')


p2 <- d_plot %>% 
  ggplot(aes(x = wy, y = val, group = site_code, color = trend_cat,
             text = paste(
               "Domain:", domain,
               "<br>Site:", site_code,
               "<br>Var:", var,
               "<br>WY:", wy,
               "<br>Val:", signif(val, 3),
               "<br>Sen slope:", signif(sen_slope, 3),
               "<br>p:", signif(p_value, 3)
             ))) +
  geom_line(aes(alpha = 0.3)) +
  scale_color_manual(
    values = c(
      pos    = 'firebrick3',
      neg    = 'dodgerblue3',
      nonsig = 'gray50'
      # flat   = 'gray50'
    ),
    # na.value = 'gray80'
  ) +
  scale_alpha_identity() +
  facet_wrap(~ var, scales = 'free_y') +
  labs(
    x = 'Water year',
    y = 'various',
    color = 'Trend',
    title = 'Other'
  ) +
  theme_few()

ggplotly(p2, tooltip = 'text')

```

<details>
  <summary>Each variable plotted separately</summary>
  
```{r all var trends (series), echo = FALSE, fig.width = 12}

plots_by_var <- vwc_plot %>% 
  group_split(var) %>% 
  # name the list by var values
  set_names(map_chr(., ~ unique(.x$var))) %>% 
  imap(function(df_var, var_name) {
    ggplot(
      df_var,
      aes(
        x = wy,
        y = vwc,
        group = site_code,
        color = trend_cat,
        text = paste(
          'Domain:', domain,
          '<br>Site:', site_code,
          '<br>Var:', var,
          '<br>WY:', wy,
          '<br>WVC:', signif(vwc, 3),
          '<br>Sen slope:', signif(sen_slope, 3),
          '<br>p:', signif(p_value, 3)
        )
      )
    ) +
      geom_line(aes(alpha = 0.3)) +
      scale_color_manual(
        values = c(
          pos    = 'firebrick3',
          neg    = 'dodgerblue3',
          nonsig = 'gray50'
        )
      ) +
      scale_alpha_identity() +
      labs(
        title = var_name,
        x = 'Water year',
        y = 'Volume-weighted concentration (mg/L)',
        color = 'Trend'
      ) +
      theme_few()
  })


plots_by_var2 <- d_plot %>% 
  group_split(var) %>% 
  set_names(map_chr(., ~ unique(.x$var))) %>% 
  imap(function(df_var, var_name) {
    ggplot(
      df_var,
      aes(
        x = wy,
        y = val,
        group = site_code,
        color = trend_cat,
        text = paste(
          'Domain:', domain,
          '<br>Site:', site_code,
          '<br>Var:', var,
          '<br>WY:', wy,
          '<br>Val:', signif(val, 3),
          '<br>Sen slope:', signif(sen_slope, 3),
          '<br>p:', signif(p_value, 3)
        )
      )
    ) +
      geom_line(aes(alpha = 0.3)) +
      scale_color_manual(
        values = c(
          pos    = 'firebrick3',
          neg    = 'dodgerblue3',
          nonsig = 'gray50'
        )
      ) +
      scale_alpha_identity() +
      labs(
        title = var_name,
        x = 'Water year',
        y = 'various',
        color = 'Trend'
      ) +
      theme_few()
  })

plotlys_by_var <- map(plots_by_var, ggplotly, tooltip = 'text')
plotlys_by_var2 <- map(plots_by_var2, ggplotly, tooltip = 'text')

htmltools::browsable(
  htmltools::tagList(lapply(plotlys_by_var, \(p) p))
)
htmltools::browsable(
  htmltools::tagList(lapply(plotlys_by_var2, \(p) p))
)
```
</details> 

### Changing N:P

```{r biplots, echo = FALSE, fig.width = 12}
x_vals <- 10^seq(-13, -1)
d_s %>% 
  filter(var %in% np_vars) %>% 
  macrosheds::ms_conversions(convert_units_from = 'mg/L', convert_units_to = 'mol/L') %>% 
  mutate(val = log(val)) %>% 
  pivot_wider(names_from = 'var', values_from = 'val') %>% 
  drop_na(NO3_N, PO4_P) %>% 
  # filter(site_code == 'BARN') %>%
  # filter(domain == 'hbef') %>%
  group_by(site_code) %>%
  arrange(wy, .by_group = TRUE) %>%
  mutate(
    ord      = row_number(),
    n        = n(),
    is_first = ord == 1,
    is_last  = ord == n(),
    pos01    = if_else(n > 1, (ord - 1) / (n - 1), 0)  # 0 = first, 1 = last
  ) %>%
  ungroup() %>%
  ggplot(aes(NO3_N, PO4_P, group = site_code)) +
  facet_wrap(~domain, scales = 'free') +
  # facet_wrap(~domain) +
  # geom_point(
  #   data = ~ filter(.x, !(is_first | is_last)),
  #   color = "gray50",
  #   alpha = 0.3
  # ) +
  geom_point(
    data = ~ filter(.x, is_first),
    color = "red",
    alpha = 0.6
  ) +
  geom_point(
    data = ~ filter(.x, is_last),
    color = "black",
    alpha = 0.6
  ) +
  geom_path(aes(color = pos01), alpha = 0.6) +
  scale_color_gradient(low = "red", high = "black", limits = c(0, 1), guide = "none") +
  theme_few() +
  xlab('NO3-N (M)') +
  ylab('PO4-P (M)') +
  # scale_x_continuous(labels = ~ signif(exp(.x), 3)) +
  # scale_y_continuous(labels = ~ signif(exp(.x), 3))
  scale_x_continuous(
    breaks = log(x_vals),
    labels = scales::label_parse()(paste0("10^", seq(-13, -1)))
  ) +
  scale_y_continuous(
    breaks = log(x_vals),
    labels = scales::label_parse()(paste0("10^", seq(-13, -1)))
  ) +
  scale_color_gradient(
    low   = "red",
    high  = "black",
    limits = c(0, 1),
    breaks = c(0, 1),
    labels = c("start", "end"),
    name   = NULL
  )

d_ratio <- d_s %>% 
  filter(var %in% np_vars) %>% 
  macrosheds::ms_conversions(convert_units_from = 'mg/L', convert_units_to = 'mol/L') %>% 
  pivot_wider(names_from = 'var', values_from = 'val') %>% 
  drop_na(NO3_N, PO4_P) %>% 
  mutate(np = NO3_N / PO4_P)

ggplot(d_ratio, aes(wy, np, group = site_code)) +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_line(alpha = 0.2) +
  stat_summary(aes(group = domain, color = domain),
               fun = median, geom = "line", size = 1.1) +
  facet_wrap(~domain, scales = "free_y") +
  ylab('N:P') +
  xlab('Water year') +
  theme(legend.position = 'none')

d_ratio <- d_s %>% 
  filter(var %in% np_vars) %>% 
  macrosheds::ms_conversions(convert_units_from = 'mg/L', convert_units_to = 'mol/L') %>% 
  pivot_wider(names_from = 'var', values_from = 'val') %>% 
  drop_na(NO3_N, PO4_P) %>% 
  mutate(ln_np = log(NO3_N / PO4_P))

ggplot(d_ratio, aes(wy, ln_np, group = site_code)) +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_line(alpha = 0.2) +
  stat_summary(aes(group = domain, color = domain),
               fun = median, geom = "line", size = 1.1) +
  facet_wrap(~domain, scales = "free_y") +
  ylab('log N:P') +
  xlab('Water year') +
  theme(legend.position = 'none')
```

### Saltiest sites (per domain) PCA

```{r saltiest site PCA, echo = FALSE, fig.width = 12}
# saltiest <- d_s %>%
#   filter(var == 'spCond') %>%
#   group_by(domain, site_code) %>% 
#   summarize(spCond = mean(val, na.rm = TRUE),
#             .groups = 'drop') %>% 
#   arrange(desc(spCond)) %>% 
#   filter(spCond >= quantile(spCond, probs = 0.75)) %>% 
#   pull(site_code)
d_salt <- vwc_s %>%
  filter(var %in% salt_vars) %>%
  filter(all(salt_vars %in% var), .by = c(wy, site_code))

saltiest <- d_salt %>% 
  group_by(domain, site_code) %>% 
  # filter(! domain %in% c('luquillo', 'mcmurdo')) %>%
  summarize(tot_salt = sum(vwc),
            .groups = 'drop') %>% 
  group_by(domain) %>%
  arrange(desc(tot_salt)) %>%
  slice(2) %>%
  ungroup() %>%
  # filter(tot_salt >= quantile(tot_salt, probs = 0.75)) %>%
  pull(site_code)
  
d_salt_pca <- d_salt %>%
  filter(site_code %in% saltiest) %>% 
  pivot_wider(names_from = var, values_from = vwc) %>% 
  group_by(domain, site_code) %>% 
  summarize(across(-wy, mean), .groups = 'drop')

pca_res <- prcomp(select(d_salt_pca, -domain, -site_code), 
                  scale. = TRUE, center = TRUE)
scores <- as.data.frame(pca_res$x) %>%
  bind_cols(d_salt_pca[, c("site_code", "domain")])

loadings <- as.data.frame(pca_res$rotation)
loadings


l_scaled <- loadings %>%
  mutate(ion = rownames(loadings)) %>%
  mutate(PC1 = PC1 * 5,
         PC2 = PC2 * 5)  # scale adjust for loadings

ggplot(scores, aes(PC1, PC2, color = domain)) +
  geom_point(size = 3) +
  geom_segment(data = l_scaled,
               aes(x = 0, y = 0, xend = PC1, yend = PC2),
               arrow = arrow(length = unit(0.02, "npc")),
               inherit.aes = FALSE) +
  geom_text_repel(data = l_scaled,
                  aes(x = PC1, y = PC2, label = ion),
                  inherit.aes = FALSE) +
  theme_minimal()

ggplot(scores, aes(PC1, PC3, color = domain)) +
  geom_point(size = 3) +
  geom_segment(data = l_scaled,
               aes(x = 0, y = 0, xend = PC1, yend = PC3),
               arrow = arrow(length = unit(0.02, "npc")),
               inherit.aes = FALSE) +
  geom_text_repel(data = l_scaled,
                  aes(x = PC1, y = PC3, label = ion),
                  inherit.aes = FALSE) +
  theme_minimal()

ggplot(scores, aes(PC2, PC3, color = domain)) +
  geom_point(size = 3) +
  geom_segment(data = l_scaled,
               aes(x = 0, y = 0, xend = PC2, yend = PC3),
               arrow = arrow(length = unit(0.02, "npc")),
               inherit.aes = FALSE) +
  geom_text_repel(data = l_scaled,
                  aes(x = PC2, y = PC3, label = ion),
                  inherit.aes = FALSE) +
  theme_minimal()

```